# Generated by Django 4.2.29 on 2026-04-07 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Combustivel',
            fields=[
                ('cmb_id', models.AutoField(primary_key=True, serialize=False)),
                ('cmb_nome', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Combustível',
                'verbose_name_plural': 'Combustíveis',
                'db_table': 'combustivel',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('mrc_id', models.AutoField(primary_key=True, serialize=False)),
                ('mrc_nome', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('mdl_id', models.AutoField(primary_key=True, serialize=False)),
                ('mdl_nome', models.CharField(max_length=100)),
                ('mdl_mrc', models.ForeignKey(db_column='mdl_mrc_id', on_delete=django.db.models.deletion.CASCADE, to='stand.marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'modelo',
                'unique_together': {('mdl_mrc', 'mdl_nome')},
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('usr_id', models.AutoField(primary_key=True, serialize=False)),
                ('usr_nome', models.CharField(max_length=100)),
                ('usr_email', models.EmailField(max_length=150, unique=True)),
                ('usr_password', models.CharField(max_length=255)),
                ('usr_telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('usr_tipo', models.CharField(default='cliente', max_length=20)),
                ('usr_criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Utilizador',
                'verbose_name_plural': 'Utilizadores',
                'db_table': 'utilizador',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('vei_id', models.AutoField(primary_key=True, serialize=False)),
                ('vei_matricula', models.CharField(max_length=20, unique=True)),
                ('vei_vin', models.CharField(max_length=50, unique=True)),
                ('vei_versao', models.CharField(blank=True, max_length=120, null=True)),
                ('vei_importado', models.BooleanField(default=False)),
                ('vei_mes', models.IntegerField(blank=True, null=True)),
                ('vei_ano', models.IntegerField()),
                ('vei_quilometros', models.IntegerField()),
                ('vei_cilindrada', models.IntegerField(blank=True, null=True)),
                ('vei_potencia_cv', models.IntegerField(blank=True, null=True)),
                ('vei_preco_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vei_estado', models.CharField(default='Disponível', max_length=30)),
                ('vei_descricao', models.TextField(blank=True, null=True)),
                ('vei_criado_em', models.DateTimeField(auto_now_add=True)),
                ('vei_atualizado_em', models.DateTimeField(auto_now=True)),
                ('vei_mdl', models.ForeignKey(db_column='vei_mdl_id', on_delete=django.db.models.deletion.CASCADE, to='stand.modelo')),
            ],
            options={
                'verbose_name': 'Veículo',
                'verbose_name_plural': 'Veículos',
                'db_table': 'veiculo',
            },
        ),
        migrations.CreateModel(
            name='TestDrive',
            fields=[
                ('tdr_id', models.AutoField(primary_key=True, serialize=False)),
                ('tdr_data', models.DateField()),
                ('tdr_hora', models.TimeField()),
                ('tdr_estado', models.CharField(default='Pendente', max_length=30)),
                ('tdr_observacoes', models.TextField(blank=True, null=True)),
                ('tdr_criado_em', models.DateTimeField(auto_now_add=True)),
                ('tdr_usr', models.ForeignKey(db_column='tdr_usr_id', on_delete=django.db.models.deletion.CASCADE, to='stand.utilizador')),
                ('tdr_vei', models.ForeignKey(db_column='tdr_vei_id', on_delete=django.db.models.deletion.CASCADE, to='stand.veiculo')),
            ],
            options={
                'verbose_name': 'Test Drive',
                'verbose_name_plural': 'Test Drives',
                'db_table': 'test_drive',
            },
        ),
        migrations.CreateModel(
            name='SimulacaoCredito',
            fields=[
                ('sim_id', models.AutoField(primary_key=True, serialize=False)),
                ('sim_entrada', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sim_taxa', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('sim_prazo_meses', models.IntegerField()),
                ('sim_prestacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sim_criado_em', models.DateTimeField(auto_now_add=True)),
                ('sim_usr', models.ForeignKey(db_column='sim_usr_id', on_delete=django.db.models.deletion.CASCADE, to='stand.utilizador')),
                ('sim_vei', models.ForeignKey(db_column='sim_vei_id', on_delete=django.db.models.deletion.CASCADE, to='stand.veiculo')),
            ],
            options={
                'verbose_name': 'Simulação de Crédito',
                'verbose_name_plural': 'Simulações de Crédito',
                'db_table': 'simulacao_credito',
            },
        ),
        migrations.CreateModel(
            name='ImagemVeiculo',
            fields=[
                ('img_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_caminho', models.CharField(max_length=255)),
                ('img_capa', models.BooleanField(default=False)),
                ('img_criado_em', models.DateTimeField(auto_now_add=True)),
                ('img_vei', models.ForeignKey(db_column='img_vei_id', on_delete=django.db.models.deletion.CASCADE, to='stand.veiculo')),
            ],
            options={
                'verbose_name': 'Imagem do Veículo',
                'verbose_name_plural': 'Imagens dos Veículos',
                'db_table': 'imagem_veiculo',
            },
        ),
        migrations.CreateModel(
            name='FinanciamentoVeiculo',
            fields=[
                ('fin_id', models.AutoField(primary_key=True, serialize=False)),
                ('fin_prazo_meses', models.IntegerField()),
                ('fin_tan', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fin_taeg', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('fin_entrada_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fin_imposto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fin_montante_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fin_prestacao', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fin_criado_em', models.DateTimeField(auto_now_add=True)),
                ('fin_vei', models.ForeignKey(db_column='fin_vei_id', on_delete=django.db.models.deletion.CASCADE, to='stand.veiculo')),
            ],
            options={
                'verbose_name': 'Financiamento do Veículo',
                'verbose_name_plural': 'Financiamentos dos Veículos',
                'db_table': 'financiamento_veiculo',
            },
        ),
        migrations.CreateModel(
            name='VeiculoCombustivel',
            fields=[
                ('vcm_id', models.AutoField(primary_key=True, serialize=False)),
                ('vcm_cmb', models.ForeignKey(db_column='vcm_cmb_id', on_delete=django.db.models.deletion.CASCADE, to='stand.combustivel')),
                ('vcm_vei', models.ForeignKey(db_column='vcm_vei_id', on_delete=django.db.models.deletion.CASCADE, to='stand.veiculo')),
            ],
            options={
                'verbose_name': 'Combustível do Veículo',
                'verbose_name_plural': 'Combustíveis dos Veículos',
                'db_table': 'veiculo_combustivel',
                'unique_together': {('vcm_vei', 'vcm_cmb')},
            },
        ),
    ]
