# Generated by Django 4.2.29 on 2026-04-08 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='vei_cmb',
            field=models.ForeignKey(blank=True, db_column='vei_cmb_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='stand.combustivel'),
        ),
        migrations.DeleteModel(
            name='VeiculoCombustivel',
        ),
    ]
